// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj53xWW9TWMq2obphJulyMKZjQlKapcYI',
    appId: '1:780691578246:web:99b45f48c71c31a858e007',
    messagingSenderId: '780691578246',
    projectId: 'attendance-system-405712',
    authDomain: 'attendance-system-405712.firebaseapp.com',
    storageBucket: 'attendance-system-405712.appspot.com',
    measurementId: 'G-T7YPHCGJQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkSXF4oy1go6zLN6c-G7HSiSOmATyUn6w',
    appId: '1:780691578246:android:6a93841856f3ee1c58e007',
    messagingSenderId: '780691578246',
    projectId: 'attendance-system-405712',
    storageBucket: 'attendance-system-405712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAauaKms09ZasmVhz-JFiTnuiWUhToFSq8',
    appId: '1:780691578246:ios:524641b3b2af869d58e007',
    messagingSenderId: '780691578246',
    projectId: 'attendance-system-405712',
    storageBucket: 'attendance-system-405712.appspot.com',
    iosBundleId: 'com.example.attendanceSystemNodejs',
  );
}
